# Google App Engine configuration for n8n Workflow Generator

runtime: python311

# Basic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Environment variables
env_variables:
  FLASK_ENV: production
  PYTHONPATH: /srv
  LOG_LEVEL: info

# Handlers for static files
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

# Main application handler
- url: /.*
  script: auto
  secure: always

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
network:
  forwarded_ports:
  - 5000

# Skip files during deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests/.*$
- ^(.*/)?test/.*$
- node_modules/
- .git/
- .gitignore
- README.md
- .dockerignore
- Dockerfile
- build.sh
- build.bat

# Beta settings
beta_settings:
  cloud_sql_instances: your-project:region:instance-name